---
- name: Disable predictable interface names
  hosts: all
  remote_user: root

  tasks:
    - name: Add parameters to kernel cmdline in grub defaults
      lineinfile:
        state: present
        dest: /etc/default/grub
        backrefs: yes
        regexp: '^(.*)GRUB_CMDLINE_LINUX="(?!.*net.ifnames=0 biosdevname=0)(.*)$'
        line: '\1GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 \2'
      notify: make grub config

  handlers:
    - name: make grub config
      shell: "grub2-mkconfig -o $(find /boot/ -name 'grub.cfg')"
